// Generated by CoffeeScript 1.3.3
(function() {
  var http, redis, zlip;

  redis = require("redis");

  http = require("http");

  zlip = require("zlib");

  console.log("hello,", "world!");

}).call(this);
